const { spawnSync } = require('node:child_process');
const os = require('node:os');

const MAX_TITLE_CHARS = 45;
// Only cut on a word boundary if the boundary is reasonably deep into the title -
// otherwise a short single-token title gets gutted down to a fragment.
const MIN_WORD_CUT_INDEX = 20;

// The prompt's opening line, exported so a sweep can recognize a transcript of one of our own
// worker calls and refuse to title it. Keep it the literal first line of buildPrompt's output.
const PROMPT_SIGNATURE = 'You title chat sessions between a developer and a coding assistant.';

const USE_PREFIX_EXAMPLES = [
  '[Emails] SES bounce rate investigation',
  '[Client Controls] Cascade validation rules',
  'KEEP',
];
const BARE_PHRASE_EXAMPLES = [
  'SES bounce rate investigation',
  'Cascade validation rules',
  'KEEP',
];

// The prefix setting is a format contract, so a title has to be checkable against it. In prefix mode
// that means a bracketed prefix with a phrase after it; in bare mode, a title that doesn't open with
// a bracket at all. The prefix length is bounded so a whole title parked in brackets doesn't read as
// a prefix, and an empty pair of brackets never counts as one.
const PREFIX_FORM = /^\[[^\]]{1,25}\] \S/;
const OPENS_WITH_BRACKET = /^\[[^\]]*\]/;

// The "reached a stopping point" marker: a fixed two-character prefix on an otherwise ordinary
// title, never part of it. Keeping it exactly one checkmark and one space is what lets every other
// rule stay written in terms of the core title - strip it, reason about what is left, put it back.
// It is orthogonal to the prefix setting: both shapes can carry it.
const DONE_MARKER = '✓ ';

const isMarked = (title) => typeof title === 'string' && title.startsWith(DONE_MARKER);
const stripMarker = (title) => (isMarked(title) ? title.slice(DONE_MARKER.length) : title);
const markTitle = (core) => (isMarked(core) ? core : DONE_MARKER + String(core == null ? '' : core));

function matchesFormat(title, usePrefix) {
  // A marked title conforms exactly when its core does. The 45-character cap is a cap on that core,
  // so a marked title runs two characters longer and is no less conforming for it.
  const s = typeof title === 'string' ? stripMarker(title) : '';
  // An empty title conforms to nothing - a session with no name is the first-title path's problem,
  // not a reformat.
  if (!s) return false;
  return usePrefix ? PREFIX_FORM.test(s) : !OPENS_WITH_BRACKET.test(s);
}

function buildPrompt({ currentTitle, prefixes = [], excerpt = '', usePrefix = true, restyle = false }) {
  const header = [`Current title: ${currentTitle ? currentTitle : '(none)'}`];
  if (usePrefix) {
    header.push(
      `Previously used prefixes (reuse one when it fits; coin a new one only for a genuinely different workstream): ${prefixes.length ? prefixes.join(', ') : '(none yet)'}`
    );
  }

  const rules = [
    usePrefix ? '- Output format: [Prefix] Short phrase' : '- Output format: Short phrase (no prefix, no brackets)',
  ];
  // The character bound is the same one matchesFormat holds a title to. Stating it here is what keeps
  // the two ends in step - a prefix longer than that reads as a whole title parked in brackets, and
  // asking for one the tool would then call non-conforming starts a reformat over a fine answer.
  if (usePrefix) rules.push('- Prefix: 1-2 words naming the project or workstream, at most 25 characters');
  rules.push('- Max 45 characters total, sentence case phrase, no quotes, no trailing period');

  // Restyle is not a re-title. The title already says what the session is about - it just isn't in
  // the shape the user asked for - so the phrase's meaning survives and only the format changes.
  // Every KEEP rule goes with it: keeping the title is the one answer that cannot fix its format.
  if (restyle) {
    rules.push('- The current title is accurate but in the wrong format - rewrite it into the required format, preserving its meaning');
    rules.push(
      usePrefix
        ? '- Use the conversation excerpt only to choose the right prefix - do not re-describe the work'
        : '- Drop the prefix and keep the phrase as it is'
    );
    rules.push('- Never output KEEP - always output a title');
    rules.push('- Output ONLY the title - no preamble, no explanation, no markdown');
  } else {
    rules.push('- The title must describe what the session is mostly about NOW');
    rules.push(
      currentTitle
        ? '- If the current title still accurately describes the conversation, output exactly: KEEP'
        : '- There is no current title yet - you must produce one.'
    );
    // Nothing in the transcript says whether a title was typed by the user or auto-generated by the
    // app, so the drift check itself has to spare a name that reads like one somebody chose.
    if (currentTitle) {
      rules.push("- If the current title reads like a deliberate personal label rather than a topic description (a person's name, a date, a note like 'Revisit Monday'), output exactly: KEEP");
    }
    rules.push('- If the excerpt has too little signal to describe the work, output exactly: KEEP');
    rules.push('- Output ONLY the title or KEEP - no preamble, no explanation, no markdown');
  }

  // KEEP can't stand as an example of an answer restyle mode has just forbidden.
  const examples = (usePrefix ? USE_PREFIX_EXAMPLES : BARE_PHRASE_EXAMPLES).filter((e) => !(restyle && e === 'KEEP'));

  // Dropping a prefix is a mechanical edit of the title itself, so the conversation has nothing to
  // contribute and the excerpt is left out rather than sent and ignored. Prefix-mode restyle still
  // needs it: choosing the prefix means knowing what the work is.
  const body = restyle && !usePrefix ? '' : excerpt;
  const excerptSection = body ? `\n\nConversation excerpt:\n${body}` : '';

  return `${PROMPT_SIGNATURE}

${header.join('\n')}

Rules:
${rules.join('\n')}

Examples:
${examples.join('\n')}${excerptSection}`;
}

const stripQuotes = (s) => s.replace(/^["'`“‘]+|["'`”’]+$/g, '').trim();

function parseResponse(raw) {
  // Quote-strip per line before any detection: models wrap multi-line answers in a
  // single pair of quotes, so the closing quote can land on a later line.
  const lines = (typeof raw === 'string' ? raw : '')
    .split('\n')
    .map((l) => stripQuotes(l.trim()))
    .filter(Boolean);
  if (!lines.length) return 'KEEP';

  // KEEP wins whether the model leads with it plus an explanation, or parks a bare
  // "keep" on its own line. Always return the canonical uppercase literal.
  if (/^keep\b/i.test(lines[0]) || lines.some((l) => /^keep[.!\s]*$/i.test(l))) return 'KEEP';

  // Prefer a bracketed title that actually carries a phrase; otherwise the first line
  // that is not a preamble header like "Here is the title:".
  let s =
    lines.find((l) => /^\[[^\]]+\]\s*\S/.test(l)) ||
    lines.find((l) => !/[:：]$/.test(l)) ||
    lines[0];
  s = stripQuotes(s).replace(/[.\s]+$/, '');

  // A title call never sees the done marker - the caller strips it before building the prompt - so a
  // checkmark coming back is the model decorating its answer, not preserving anything. Minting a
  // marker here would mark a session nothing judged to be finished, so it comes straight off.
  s = s.replace(/^✓\s*/, '');

  // Degenerate output - nothing, punctuation/symbols only, or a bare "[Prefix]".
  if (!s || /^[\s\p{P}\p{S}]*$/u.test(s) || /^\[[^\]]*\]$/.test(s)) return 'KEEP';

  // "[Emails]Fix" and "[Emails]   Fix" mean what "[Emails] Fix" means, and the format check counts
  // only the last as a prefix. Rewriting the spacing is no judgement about the title, and without it
  // the tool can write a title it classifies as non-conforming on the very next look - then spend a
  // model call reformatting an answer that was already right.
  s = s.replace(/^(\[[^\]]+\])\s*/, '$1 ');

  const chars = [...s];
  if (chars.length > MAX_TITLE_CHARS) {
    let cut = chars.slice(0, MAX_TITLE_CHARS).join('');
    const sp = cut.lastIndexOf(' ');
    if (sp > MIN_WORD_CUT_INDEX) cut = cut.slice(0, sp);
    s = cut.trim();
  }
  return s || 'KEEP';
}

function runClaude(prompt, model, spawn = spawnSync) {
  const res = spawn('claude', ['-p', '--model', model], {
    input: prompt,
    encoding: 'utf8',
    cwd: os.tmpdir(),
    timeout: 90_000,
    env: { ...process.env, CLAUDE_SESSION_NAMER_WORKER: '1' },
  });
  if (res.error) throw res.error;
  if (res.status !== 0) {
    const detail = String(res.stderr || '').trim().slice(0, 200);
    throw new Error(
      res.signal
        ? `claude killed by signal ${res.signal}: ${detail}`
        : `claude exited ${res.status}: ${detail}`
    );
  }
  return res.stdout;
}

function generateTitle({ currentTitle, prefixes, excerpt, usePrefix = true, restyle = false, model = 'haiku', runner = runClaude }) {
  return parseResponse(runner(buildPrompt({ currentTitle, prefixes, excerpt, usePrefix, restyle }), model));
}

// The done judgment's own opening line, exported for the same reason PROMPT_SIGNATURE is: a sweep
// has to recognize the transcript of one of our own calls and leave it alone. Keep it the literal
// first line of buildDonePrompt's output.
const DONE_PROMPT_SIGNATURE = 'You judge whether a chat session between a developer and a coding assistant has finished.';

// One question, two allowed answers. The title goes in as context for what the session set out to
// do; the excerpt is the tail, because whether work stopped is a fact about how it ended.
function buildDonePrompt({ currentTitle, excerpt = '' }) {
  const rules = [
    '- Answer DONE if the work reached a stopping point: the last thing asked for was delivered, answered, or dropped, and nothing is left half-finished.',
    '- Answer ONGOING if the session ends mid-task: an open question, a failing command, an unanswered request, a plan with steps left, or work still in progress.',
    '- If the ending is ambiguous, answer ONGOING.',
    '- Output ONLY the single word DONE or ONGOING - no preamble, no explanation, no punctuation.',
  ];
  const excerptSection = excerpt ? `\n\nEnd of the conversation:\n${excerpt}` : '';
  return `${DONE_PROMPT_SIGNATURE}

Session title: ${currentTitle ? currentTitle : '(none)'}

Rules:
${rules.join('\n')}${excerptSection}`;
}

// ONGOING is the answer anything unclear reads as. Marking a session done that is not is the visible
// error - a checkmark on work the user is in the middle of - while missing one costs nothing but a
// re-judgment on the next sweep.
function parseDone(raw) {
  const first = (typeof raw === 'string' ? raw : '').split('\n').map((l) => l.trim()).filter(Boolean)[0];
  return Boolean(first) && /^done\b/i.test(stripQuotes(first));
}

function judgeDone({ currentTitle, excerpt, model = 'haiku', runner = runClaude }) {
  return parseDone(runner(buildDonePrompt({ currentTitle, excerpt }), model));
}

module.exports = {
  buildPrompt, parseResponse, runClaude, generateTitle, matchesFormat, PROMPT_SIGNATURE,
  buildDonePrompt, parseDone, judgeDone, DONE_PROMPT_SIGNATURE,
  DONE_MARKER, isMarked, stripMarker, markTitle,
};
